# site settings
title: Carlos Eduardo Gonçalves
subtitle: Software Developer
email: pnqh.tbapnyirf@tznvy.pbz #encoded as rot13
description: Welcome to my personal website where I share my personal <br />projects, toughts and professional skills.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://cadu-goncalves.github.io
author:
street_address:
city: Florianópolis
state: SC
zip_code:
country: Brazil
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/etriphany
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/cadu.goncalves
linkedin_url: https://www.linkedin.com/in/cadugoncalves
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cadu_goncalves
corporate_url: http://etriphany.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-137357228-1

# build settings
markdown: kramdown

sass:
  style: compressed
